# Generated by Django 3.2 on 2022-02-01 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_fech', models.DateTimeField(null=True, verbose_name='fecha')),
                ('pedido_nro', models.CharField(default='', max_length=100, verbose_name='pedido nro')),
                ('pedido_est', models.CharField(default='pagado', max_length=100, verbose_name='Estado')),
                ('mesa_id', models.ForeignKey(db_column='mesa_id', on_delete=django.db.models.deletion.RESTRICT, related_name='PedidosxMesa', to='api.mesa', verbose_name='mesa')),
                ('usu_id', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.RESTRICT, related_name='PedidosxUsuario', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoPlatos',
            fields=[
                ('pedidoplato_id', models.AutoField(primary_key=True, serialize=False)),
                ('pedidoplato_cant', models.IntegerField(default=1, verbose_name='cantidad')),
                ('pedido_id', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.RESTRICT, related_name='PlatosxPedido', to='api.pedido', verbose_name='pedido')),
                ('plato_id', models.ForeignKey(db_column='plato_id', on_delete=django.db.models.deletion.RESTRICT, related_name='PedidosXPlato', to='api.plato', verbose_name='plato')),
            ],
        ),
    ]
